# DAGify Configuration
version: 1.0
defaults:
  schedule_interval: "0 0 * * *"  # Daily at midnight
  start_date: "2024-01-01"
  catchup: false
  tags: ["dataflow", "migrated"]

dataflow_mapping:
  job_name: "dag_id"
  template_path: "template"
  parameters: "parameters"
  network: "network"
  service_account: "service_account_email"
  max_workers: "max_workers"
  machine_type: "machine_type"

dag_defaults:
  owner: "airflow"
  depends_on_past: false
  email_on_failure: true
  email_on_retry: false
  retries: 1
  retry_delay_minutes: 5